apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx # (Must match labels below in the template)
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx # (Must match selector labels above)
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2 # (Change to your desired image)
          ports:
            - containerPort: 80 # (Ensure port matches service targetPort)
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx # (MUST match Deployment labels correctly)
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # (Must align with containerPort or app logic)